# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'NetTool' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetTool
  
  pod 'SnapKit'
  pod 'JKSwiftExtension'
  #关于设备
  pod 'DeviceKit'

  pod 'RxSwift'
  pod 'RxCocoa'
  #Net
  pod 'Alamofire'
  pod 'Moya/RxSwift'
  #SwiftJson
  pod 'SwiftyJSON'
  #序列化
  pod 'ObjectMapper'
  pod 'HandyJSON'
  #多控制器tableView
  pod 'LTScrollView'
  pod 'JFPopup'
  #图像处理
  pod 'GPUImage'
  #动画相关
  pod 'lottie-ios'
  #缓存数据
  pod 'YYCache'
  #Svg
#  pod 'SVGKit' //无用，莫名其妙报错
  pod 'SwiftSVG'
  pod "MBProgressHUD"
  
  pod "ESTabBarController-swift"
  
  pod 'iosMath'
  pod 'YYText'
  pod 'RichTextView'



end


post_install do |installer|

  installer.generated_projects.each do |project|

    project.targets.each do |target|

        target.build_configurations.each do |config|
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
        end

    end

  end

end

