# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'NetTool' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetTool
  
  pod 'SnapKit'
  pod 'JKSwiftExtension'

  pod 'RxSwift'
  pod 'RxCocoa'
  #Net
  pod 'Alamofire'
  pod 'Moya/RxSwift'
  #SwiftJson
  pod 'SwiftyJSON'
  #序列化
  pod 'ObjectMapper'
  pod 'HandyJSON'





end


post_install do |installer|

  installer.generated_projects.each do |project|

    project.targets.each do |target|

        target.build_configurations.each do |config|
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
        end

    end

  end

end

